#!/bin/bash

# Get Wifi IP
wlanip=`/sbin/ifconfig wlan0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`

# If we got a Wifi IP, echo it and exit success
if [ "" != "${wlanip}" ]; then
	echo $wlanip
	exit 0
fi


# Get ethernet IP
ethip=`/sbin/ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`

# If we got an ethernet IP, echo it and exit success
if [ "" != "${ethip}" ]; then
	echo $ethip
	exit 0
fi


# If we got here, we didn't find any IP
# Echo error to stderr
echo "Could not find IP on wlan0 (Wifi) or eth0 (Ethernet)" 1>&2
exit 1

