#!/bin/bash

# RUN AS ROOT / use sudo

if [ ! -e /etc/hosts.orig ]; then
	cp /etc/hosts /etc/hosts.orig
fi

echo "Copying original: /etc/hosts.orig -> /etc/hosts"
cp /etc/hosts.orig /etc/hosts
echo "" >> /etc/hosts
echo "# RGT_3.14 sethosts (`date +%Y%m%d-%H%M`):" >> /etc/hosts

for d in */ ; do
	if [ -e "$d/ip" ]; then
		echo "`cat $d/ip` rgt_${d%?}" >> /etc/hosts
	fi
done

